#!/usr/bin/env bash
#
# release-replit-template.sh — build a flattened, Replit-importable template artifact.
#
# Output: dist/replit-template/ (runnable scaffold at repo root; no templates/ tree).
#
# Usage:
#   bash scripts/release-replit-template.sh
#   RELEASE_DEST=/tmp/out bash scripts/release-replit-template.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SCAFFOLD="${REPO_ROOT}/templates/generated-project/scaffold"
DEST="${RELEASE_DEST:-${REPO_ROOT}/dist/replit-template}"

canonical_path() {
  python3 - "$1" <<'PY'
from pathlib import Path
import sys

print(Path(sys.argv[1]).expanduser().resolve(strict=False))
PY
}

is_same_or_ancestor() {
  local candidate="$1" protected="$2"
  [ "$candidate" = "$protected" ] || [[ "$protected" == "$candidate/"* ]]
}

paths_overlap() {
  local left="$1" right="$2"
  is_same_or_ancestor "$left" "$right" || is_same_or_ancestor "$right" "$left"
}

# The release script deletes and recreates RELEASE_DEST. Canonicalize before
# creating anything, reject ancestors of broad protected trees, and reject any
# overlap with source/control-plane trees. This closes the `$REPO_ROOT/..`
# ancestor case that exact string matching cannot detect.
DEST_ABS="$(canonical_path "$DEST")"
if [ "$DEST_ABS" = "/" ] || [ "$(dirname "$DEST_ABS")" = "/" ]; then
  echo "release-replit-template: refusing unsafe RELEASE_DEST: $DEST_ABS" >&2
  exit 1
fi
for protected in "$(canonical_path "$HOME")" "$(canonical_path "$REPO_ROOT")" "$(canonical_path /tmp)"; do
  if is_same_or_ancestor "$DEST_ABS" "$protected"; then
    echo "release-replit-template: refusing unsafe RELEASE_DEST: $DEST_ABS" >&2
    exit 1
  fi
done
for protected in \
  "$SCAFFOLD" \
  "$REPO_ROOT/templates" \
  "$REPO_ROOT/custom_instruction" \
  "$REPO_ROOT/.agents" \
  "$REPO_ROOT/.claude"; do
  if paths_overlap "$DEST_ABS" "$(canonical_path "$protected")"; then
    echo "release-replit-template: refusing unsafe RELEASE_DEST: $DEST_ABS" >&2
    exit 1
  fi
done
if [ -e "$DEST_ABS" ] && [ ! -d "$DEST_ABS" ]; then
  echo "release-replit-template: RELEASE_DEST exists and is not a directory: $DEST_ABS" >&2
  exit 1
fi
DEST="$DEST_ABS"
DEST_MARKER=".aiae-replit-release"
if [ -d "$DEST" ] \
    && [ -n "$(find "$DEST" -mindepth 1 -maxdepth 1 -print -quit)" ] \
    && [ ! -f "$DEST/$DEST_MARKER" ]; then
  echo "release-replit-template: refusing to replace non-empty unowned destination: $DEST" >&2
  echo "  expected ownership marker: $DEST/$DEST_MARKER" >&2
  exit 1
fi
if [ "${RELEASE_VALIDATE_DEST_ONLY:-0}" = "1" ]; then
  echo "release-replit-template: destination is safe: $DEST"
  exit 0
fi
WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT

echo "==> Materialize scaffold into ${WORK}"
SCAFFOLD_ROOT="${SCAFFOLD}" \
  TEMPLATE_REPO_ROOT="${REPO_ROOT}" \
  MATERIALIZE_DEST="${WORK}" \
  bash "${SCAFFOLD}/scripts/materialize-project.sh" replitmvp

echo "==> Copy flattened artifact to ${DEST}"
rm -rf "${DEST}"
mkdir -p "${DEST}"

rsync -a \
  --exclude node_modules \
  --exclude target \
  --exclude '.git' \
  "${WORK}/" "${DEST}/"
printf 'Generated by scripts/release-replit-template.sh\n' > "${DEST}/${DEST_MARKER}"

# AGENTS.md and replit.md are materialized from explicit scaffold templates.
# Do not overwrite either file here.

echo "==> Validate release artifact"
test -f "${DEST}/backend/pom.xml"
test -f "${DEST}/${DEST_MARKER}"
test -f "${DEST}/scripts/verify-gates.sh"
test -f "${DEST}/frontend/nginx.conf.template"
! test -d "${DEST}/templates/generated-project/scaffold" \
  || { echo "release must not embed control-plane scaffold path"; exit 1; }
# Both runtime discovery surfaces must be present.
test -f "${DEST}/AGENTS.md" \
  || { echo "release artifact missing AGENTS.md (Replit entry point)"; exit 1; }
test -f "${DEST}/replit.md" \
  || { echo "release artifact missing replit.md"; exit 1; }
test -f "${DEST}/CLAUDE.md" \
  || { echo "release artifact missing CLAUDE.md (Claude Code entry point)"; exit 1; }
test -f "${DEST}/.mcp.json" \
  || { echo "release artifact missing .mcp.json (Context7 project MCP)"; exit 1; }
grep -q 'https://mcp.context7.com/mcp/oauth' "${DEST}/.mcp.json" \
  || { echo "release artifact has an invalid Context7 MCP endpoint"; exit 1; }
! grep -Eq 'CONTEXT7_API_KEY|ctx7sk-' "${DEST}/.mcp.json" \
  || { echo "release artifact must not contain a Context7 credential"; exit 1; }
test -d "${DEST}/.claude/skills" \
  || { echo "release artifact missing .claude/skills"; exit 1; }
test -d "${DEST}/.claude/rules" \
  || { echo "release artifact missing .claude/rules"; exit 1; }
test -d "${DEST}/.agents/skills" \
  || { echo "release artifact missing .agents/skills"; exit 1; }
test -f "${DEST}/.claude/tasks/README.md" \
  || { echo "release artifact missing .claude/tasks/README.md"; exit 1; }

# Every shipped skill must resolve without the templates/ tree, which is absent
# from the artifact. This is the check that keeps a downloaded project working.
if grep -rqn "templates/generated-project" "${DEST}/.claude/skills" "${DEST}/.agents/skills" 2>/dev/null; then
  echo "release artifact ships a skill referencing templates/generated-project:"
  grep -rn "templates/generated-project" "${DEST}/.claude/skills" "${DEST}/.agents/skills"
  exit 1
fi

echo "==> release-replit-template: wrote ${DEST}"
